imagex/imagex/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from search.views import download, like, view_image
from accounts.views import change_password
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^', include('search.urls')),
                  url(r'^login/$', auth_views.login, name="login"),
                  url(r'^logout/$', auth_views.logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
                  path('search/', include('search.urls')),
                  path('admin/', admin.site.urls),
                  path('account/', include('allauth.urls')),
                  path('upload/', include('upload.urls')),
                  path('profiles/', include('profiles.urls')),
                  url(r'^download/$', download, name="download"),
                  url(r'^view/$', view_image, name="view_image"),
                  path('<int:pk>/like/', like, name='like_image'),
                  url(r'^change_password/$', change_password, name='change_password'),
                  url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
                  url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
                  url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      auth_views.password_reset_confirm, name='password_reset_confirm'),
                  url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
                  url(r'^invitations/', include('invitations.urls', namespace='invitations')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagex/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
  path('<username>/edit', views.edit_profile, name='edit_profile'),
  path('<int:pk>/delete/', views.delete, name='delete_image'),
  path('<int:pk>/update/', views.update,name='update_profile'),
  path('<username>', views.view_profile, name='view_profile')
]

imagex/profiles/models.py
from django.db import models

# Create your models here.

imagex/profiles/views.py
from django.shortcuts import render
from search.models import Image
from accounts.models import Member
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.db.models import F

from django.urls import reverse_lazy


def edit_profile(request, username):
    if username == request.user.username:
        current_user_username = request.user.username
        current_user_pk = Member.objects.filter(username=current_user_username)[0].id
        member_description = Member.objects.filter(username=current_user_username)[0].description
        images = Image.objects.filter(photographer=current_user_pk)
        img_with_popularity = images.annotate(
            popularity=F('num_of_downloads') + F('num_of_likes')
        )
        users_images = img_with_popularity.order_by('-popularity')

        return render(request, 'profiles/profiles.html', {'images': users_images, 'member_description': member_description, 'member_pk': current_user_pk})


def update(request, pk):
    current_user_username = request.user.username
    member = Member.objects.get(username=current_user_username)

    member.description = request.POST.get('description')
    member.save(update_fields=["description"])

    request.user.first_name = request.POST.get('first_name')
    request.user.last_name = request.POST.get('last_name')
    request.user.email = request.POST.get('email')
    request.user.save(update_fields=['first_name', 'last_name', 'email'])

    return redirect(reverse_lazy('profiles:edit_profile', kwargs={'username': current_user_username}))


def view_profile(request, username):
    member_username = username
    current_user_pk = Member.objects.filter(username=member_username)[0].id
    member = User.objects.filter(username=username)[0]
    first_name = member.first_name
    last_name = member.last_name
    email = member.email
    member_description = Member.objects.filter(username=member_username)[0].description
    images = Image.objects.filter(photographer=current_user_pk)
    img_with_popularity = images.annotate(
        popularity=F('num_of_downloads') + F('num_of_likes')
    )
    users_images = img_with_popularity.order_by('-popularity')

    return render(request, 'profiles/member_profile.html',
                  {'images': users_images, 'username': member_username, 'member_description': member_description,
                   'member_pk': current_user_pk, 'first_name': first_name, 'last_name': last_name, 'email': email})


def delete(request, pk):
    current_user_username = request.user.username
    Image.objects.get(id=pk).delete()
    return redirect(reverse_lazy('profiles:edit_profile', kwargs={'username': current_user_username}))

imagex/profiles/templates/profiles/member_profile.html
{% extends "base.html" %}
{% block title %}Profile - imageX{% endblock %}
{% block content %}

    <div class="container-fluid py-5 text-center">
        <h4>{{ first_name }} {{ last_name }} ({{ username }})</h4>
        <p> {{ member_description }} </p>
        <p><a href="mailto:{{ email }}">{{ email }}</a></p>

        {% if username == request.user.username %}
            <a class="btn btn-outline-primary" href="/profiles/{{ request.user.username }}/edit">Edit Profile</a>
            <a class="btn btn-outline-primary" href="/change_password/">Change Password</a>
        {% endif %}

    </div>
    <div class="album py-5">
        <div class="container">
            <div class="row">
                {% for i in images %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <a href="/view/?img={{ i.img.name }}"><img class="card-img-top"
                                                                       src="http://localhost:8000/images/{{ i.img }}"
                                                                       alt="{{ i.description }}"
                                                                       id="{{ i.img.name }}"></a>
                            <div class="card-body">
                                <h5 class="card-title">{{ i.title }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">posted on {{ i.upload_date }}</h6>
                                <p class="card-body">{{ i.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        {% if request.user.is_authenticated %}
                                            {% if i.photographer.username.username != request.user.username %}
                                                <form method="POST"
                                                      action="{% url 'like_image' i.pk %}">{% csrf_token %}
                                                    <button type="submit" class="btn btn-sm btn-outline-primary">Like
                                                    </button>
                                                </form>
                                            {% endif %}
                                        {% endif %}
                                        <form method="GET" action="/download/">
                                            <button type="submit" class="btn btn-sm btn-outline-primary"
                                                    name="{{ i.img.name }}">Download
                                            </button>
                                        </form>
                                    </div>
                                    <small class="text-muted">{{ i.num_of_likes }} Likes</small>
                                    <small class="text-muted">{{ i.num_of_downloads }} Downloads</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

imagex/profiles/templates/profiles/profiles.html
{% extends "base.html" %}
{% block title %}Profile - imageX{% endblock %}
{% block content %}

    <div class="container py-5 text-center">
        <h1>Edit Profile</h1>

        <form class="py-3" method="POST" action="{% url 'profiles:update_profile' member_pk %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="title">First name</label>
                <input class="col-sm-10 form-control" type="text" name="first_name" id="first_name"
                       value="{{ request.user.first_name }}">
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="description">Last name</label>
                <input class="form-control col-sm-10" name="last_name" id="last_name"
                       value="{{ request.user.last_name }}">
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="description">Email</label>
                <input class="form-control col-sm-10" name="email" id="email" value="{{ request.user.email }}">
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="description">Description</label>
                <textarea class="form-control col-sm-10" name="description" id="description"
                          rows="2">{{ member_description }}</textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary mb-2">Save Changes</button>
            </div>
        </form>

    </div>



    <div class="album py-5">
        <div class="container">
            <div class="row">
                {% for i in images %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top"
                                 src="http://127.0.0.1:8000/images/{{ i.img }}"
                                 alt="{{ i.description }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ i.title }}</h5>
                                <div class="d-flex justify-content-between align-items-center">
                                    <form action="{% url 'profiles:delete_image' i.pk %}" method="POST">{% csrf_token %}
                                        <div class="btn-group">
                                            <button type="submit" data-toggle="confirmation"
                                                    class="btn btn-sm btn-outline-primary" name="{{ i.pk }}">Delete
                                            </button>
                                        </div>
                                    </form>
                                    <small class="text-muted">{{ i.num_of_likes }} Likes</small>
                                    <small class="text-muted">{{ i.num_of_downloads }} Downloads</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    {% load static %}
    <script src="{% static 'bootstrap-confirmation.js' %}"></script>
    <script>
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            container: 'body'
        });
    </script>
{% endblock %}